"""
Django settings for techsonia project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES_DIR = os.path.join(BASE_DIR, 'nblog/templates')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p$ks)ozh-%-4&nrq0)f5e&x081+ne!#1ou*@0h#%888^d1nc8*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nblog',
    'ckeditor',
    'paypal.standard.ipn',
    'crispy_forms',
    'tinymce',
    'django.contrib.sites',
    'django_social_share',
    'taggit',
    'widget_tweaks',
  #  'crispy_bootstrap5',
   # 'crispy_forms_bootstrap5',
     'nblog.templatetags', 
   # 'reading_time',
   #'wagtail-readingtime',



    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     
]

'crispy_forms.context_processors.crispy_forms'
'crispy_forms.context_processors.form_errors'


ROOT_URLCONF = 'newhatchblog.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',


        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
               
                

            ],

            'builtins': [
                'bootstrap4.templatetags.bootstrap4',
            ]
        },
    },
]


WSGI_APPLICATION = 'newhatchblog.wsgi.application'

# Import crispy_forms
import crispy_forms
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.postgresql_psycopg2',
   #     'NAME': 'nblog',
    #    'USER':'postgres',
     #   'PASSWORD':'samename',
      #  'PORT':'5432',
       # 'HOST':'localhost'
    #}
#}
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL ='/images/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'newhatchblog/static')
]
STATIC_ROOT ='/home/triljeoz/trillumize.com/static/'
MEDIA_ROOT = '/home/triljeoz/trillumize.com/media/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

#paypal setting
PAYPAL_TEST = True
PAYPAY_RECEIVES_EMAIL ='saahndongransom@gmail.com'



# Either enable sending mail messages to the console:
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# or smpt EmailBackend

#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'saahndongransom@gmail.com'
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = 'saahndongransom@gmail.com'

# settings.py




#paypay setting
PAYPAL_TEST = True
PAYPAl_RECEIVER_EMAIL = 'sandbox@gmail.com'

TEMPLATE_LOADERS = (
    'django.article_utils.loaders.nblog.load_template_source',
)

ALLOWED_HOSTS = ['*']
SITE_ID=1

APPEND_SLASH = False


# settings.py

...

# crispy forms settings
CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


