# Generated by Django 4.1.7 on 2023-03-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedPost',
        ),
    ]
