# Generated by Django 4.1.7 on 2023-03-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nblog', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
