# Generated by Django 4.1.7 on 2023-03-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nblog', '0004_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
    ]
